# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='game_service.proto',
  package='pluto',
  serialized_pb=_b('\n\x12game_service.proto\x12\x05pluto\"\x06\n\x04Void\"\x1d\n\x0eRequestMessage\x12\x0b\n\x03msg\x18\x01 \x02(\t\"\x1e\n\x0fResponseMessage\x12\x0b\n\x03msg\x18\x01 \x02(\t2:\n\x0cIEchoService\x12*\n\x04\x65\x63ho\x12\x15.pluto.RequestMessage\x1a\x0b.pluto.Void2@\n\x0bIEchoClient\x12\x31\n\necho_reply\x12\x16.pluto.ResponseMessage\x1a\x0b.pluto.VoidB\x03\x90\x01\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='pluto.Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=35,
)


_REQUESTMESSAGE = _descriptor.Descriptor(
  name='RequestMessage',
  full_name='pluto.RequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='pluto.RequestMessage.msg', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=66,
)


_RESPONSEMESSAGE = _descriptor.Descriptor(
  name='ResponseMessage',
  full_name='pluto.ResponseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='pluto.ResponseMessage.msg', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['Void'] = _VOID
DESCRIPTOR.message_types_by_name['RequestMessage'] = _REQUESTMESSAGE
DESCRIPTOR.message_types_by_name['ResponseMessage'] = _RESPONSEMESSAGE

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), dict(
  DESCRIPTOR = _VOID,
  __module__ = 'game_service_pb2'
  # @@protoc_insertion_point(class_scope:pluto.Void)
  ))
_sym_db.RegisterMessage(Void)

RequestMessage = _reflection.GeneratedProtocolMessageType('RequestMessage', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTMESSAGE,
  __module__ = 'game_service_pb2'
  # @@protoc_insertion_point(class_scope:pluto.RequestMessage)
  ))
_sym_db.RegisterMessage(RequestMessage)

ResponseMessage = _reflection.GeneratedProtocolMessageType('ResponseMessage', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEMESSAGE,
  __module__ = 'game_service_pb2'
  # @@protoc_insertion_point(class_scope:pluto.ResponseMessage)
  ))
_sym_db.RegisterMessage(ResponseMessage)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\220\001\001'))

_IECHOSERVICE = _descriptor.ServiceDescriptor(
  name='IEchoService',
  full_name='pluto.IEchoService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=100,
  serialized_end=158,
  methods=[
  _descriptor.MethodDescriptor(
    name='echo',
    full_name='pluto.IEchoService.echo',
    index=0,
    containing_service=None,
    input_type=_REQUESTMESSAGE,
    output_type=_VOID,
    options=None,
  ),
])

IEchoService = service_reflection.GeneratedServiceType('IEchoService', (_service.Service,), dict(
  DESCRIPTOR = _IECHOSERVICE,
  __module__ = 'game_service_pb2'
  ))

IEchoService_Stub = service_reflection.GeneratedServiceStubType('IEchoService_Stub', (IEchoService,), dict(
  DESCRIPTOR = _IECHOSERVICE,
  __module__ = 'game_service_pb2'
  ))



_IECHOCLIENT = _descriptor.ServiceDescriptor(
  name='IEchoClient',
  full_name='pluto.IEchoClient',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=160,
  serialized_end=224,
  methods=[
  _descriptor.MethodDescriptor(
    name='echo_reply',
    full_name='pluto.IEchoClient.echo_reply',
    index=0,
    containing_service=None,
    input_type=_RESPONSEMESSAGE,
    output_type=_VOID,
    options=None,
  ),
])

IEchoClient = service_reflection.GeneratedServiceType('IEchoClient', (_service.Service,), dict(
  DESCRIPTOR = _IECHOCLIENT,
  __module__ = 'game_service_pb2'
  ))

IEchoClient_Stub = service_reflection.GeneratedServiceStubType('IEchoClient_Stub', (IEchoClient,), dict(
  DESCRIPTOR = _IECHOCLIENT,
  __module__ = 'game_service_pb2'
  ))


# @@protoc_insertion_point(module_scope)
